WIP try to use multple ci scripts

diff --git a/script/travis-ci b/script/travis-ci
--- a/script/travis-ci
+++ b/script/travis-ci
@@ -42,16 +42,6 @@ else
     echo "INFO: bundled"
 fi
 
-# # rspec tests
-bundle exec rake spec
-RETVAL=$?
-if [ $RETVAL != 0 ]; then
-    echo "FAIL: failed rspec tests"
-    exit $RETVAL
-else
-    echo "INFO: passed rspec tests"
-fi
-
 # unit tests
 # ruby lib/calabash-cucumber/version.rb
 #RETVAL=$?
@@ -62,79 +52,79 @@ fi
 #    echo "INFO: passed unit tests"
 #fi
 
-# # on-simulator tests of features in test/cucumber
-cd test/cucumber
-rm -rf Gemfile
-rm -rf Gemfile.lock
-rm -rf .bundle
-rm -rf vendor
-bundle install --deployment
+# on-simulator tests of features in test/cucumber
+# cd test/cucumber
+# rm -rf Gemfile
+# rm -rf Gemfile.lock
+# rm -rf .bundle
+# rm -rf vendor
+# bundle install --deployment
 
-# remove any stale targets
-bundle exec calabash-ios sim reset
+# # remove any stale targets
+# bundle exec calabash-ios sim reset
 
-# Disable exiting on error so script continues if tests fail
-set +o errexit
+# # Disable exiting on error so script continues if tests fail
+# set +o errexit
 
-export APP_BUNDLE_PATH="./LPSimpleExample-cal.app"
+# export APP_BUNDLE_PATH="./LPSimpleExample-cal.app"
 
-RETVAL=0
+# RETVAL=0
 
-bundle exec cucumber -p sim61_4in $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim61_4in $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
 
-bundle exec cucumber -p sim71_4in $CUCUMBER_ARGS
- RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim71_4in $CUCUMBER_ARGS
+#  RETVAL=$(($RETVAL+$?))
 
-# Will not pass on travis although a similar rspec test does.
-# Instead we run on the 4in 7.0 64 bit simulator.
-if [ -z $TRAVIS ]; then
-    bundle exec cucumber -p sim71_64b $CUCUMBER_ARGS
-    RETVAL=$(($RETVAL+$?))
-else
-    # bundle exec cucumber -p sim71_64b $CUCUMBER_ARGS
-    # EXPECT_FAIL=$?
-    # if [ $EXPECT_FAIL = 0 ]; then
-    #     echo "FAIL: expected iPhone iOS 7.1 64b to fail"
-    #     exit $EXPECT_FAIL
-    # fi
-    bundle exec cucumber -p sim70_64b $CUCUMBER_ARGS
-    RETVAL=$(($RETVAL+$?))
-fi
+# # Will not pass on travis although a similar rspec test does.
+# # Instead we run on the 4in 7.0 64 bit simulator.
+# if [ -z $TRAVIS ]; then
+#     bundle exec cucumber -p sim71_64b $CUCUMBER_ARGS
+#     RETVAL=$(($RETVAL+$?))
+# else
+#     # bundle exec cucumber -p sim71_64b $CUCUMBER_ARGS
+#     # EXPECT_FAIL=$?
+#     # if [ $EXPECT_FAIL = 0 ]; then
+#     #     echo "FAIL: expected iPhone iOS 7.1 64b to fail"
+#     #     exit $EXPECT_FAIL
+#     # fi
+#     bundle exec cucumber -p sim70_64b $CUCUMBER_ARGS
+#     RETVAL=$(($RETVAL+$?))
+# fi
 
-bundle exec cucumber -p sim61r $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
-bundle exec cucumber -p sim71r $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim61r $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim71r $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
 
-bundle exec cucumber -p sim61_ipad_r $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
-bundle exec cucumber -p sim71_ipad_r $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim61_ipad_r $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim71_ipad_r $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
 
-if [ -z $TRAVIS ]; then
-    bundle exec cucumber -p sim71_ipad_r_64b $CUCUMBER_ARGS
-    RETVAL=$(($RETVAL+$?))
-else
-    # bundle exec cucumber -p sim71_ipad_r_64b $CUCUMBER_ARGS
-    # EXPECT_FAIL=$?
-    # if [ $EXPECT_FAIL = 0 ]; then
-    #     echo "FAIL: expected iPad iOS 7.1 64b to fail"
-    #     exit $EXPECT_FAIL
-    # fi
-    bundle exec cucumber -p sim70_ipad_r_64b $CUCUMBER_ARGS
-    RETVAL=$(($RETVAL+$?))
-fi
+# if [ -z $TRAVIS ]; then
+#     bundle exec cucumber -p sim71_ipad_r_64b $CUCUMBER_ARGS
+#     RETVAL=$(($RETVAL+$?))
+# else
+#     # bundle exec cucumber -p sim71_ipad_r_64b $CUCUMBER_ARGS
+#     # EXPECT_FAIL=$?
+#     # if [ $EXPECT_FAIL = 0 ]; then
+#     #     echo "FAIL: expected iPad iOS 7.1 64b to fail"
+#     #     exit $EXPECT_FAIL
+#     # fi
+#     bundle exec cucumber -p sim70_ipad_r_64b $CUCUMBER_ARGS
+#     RETVAL=$(($RETVAL+$?))
+# fi
 
-bundle exec cucumber -p sim61_sl $CUCUMBER_ARGS
-RETVAL=$(($RETVAL+$?))
+# bundle exec cucumber -p sim61_sl $CUCUMBER_ARGS
+# RETVAL=$(($RETVAL+$?))
 
-set -o errexit
+# set -o errexit
 
-if [ $RETVAL != 0 ]; then
-    echo "FAIL: failed $RETVAL out of 9 simulators"
-    exit $RETVAL
-fi
+# if [ $RETVAL != 0 ]; then
+#     echo "FAIL: failed $RETVAL out of 9 simulators"
+#     exit $RETVAL
+# fi
 
 #echo "source 'http://rubygems.org'" > Gemfile
 #echo "gem 'calabash-cucumber', :path => '${CALABASH_GEMSPEC_PATH}'" >> Gemfile
